//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChargeAfter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public long ReqID { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<decimal> RequestAmount { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string RequestStatus { get; set; }
    }
}
