//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChargeAfter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestOffer
    {
        public long OffID { get; set; }
        public Nullable<long> ReqID { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<decimal> ApprovedAmmount { get; set; }
        public Nullable<decimal> TotalPayback { get; set; }
        public Nullable<int> IncreasePercent { get; set; }
        public Nullable<decimal> MonthlyAmount { get; set; }
        public Nullable<int> MonthCount { get; set; }
        public string Lender { get; set; }
    }
}
