//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChargeAfter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string EmploymentStatus { get; set; }
        public string EstimatedCreditRange { get; set; }
        public string HousingStatus { get; set; }
        public string GrossAnnualIndividual { get; set; }
        public string NetMonthlyIncome { get; set; }
        public string SalaryFrequency { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Mobile { get; set; }
        public string Lender { get; set; }
        public string DriverLicense { get; set; }
        public string monthlyRent { get; set; }
        public string YearatResidence { get; set; }
        public string DriverLicenseState { get; set; }
        public Nullable<System.DateTime> DriverLicensExpirationDate { get; set; }
        public string SocialSecurityNumber { get; set; }
    }
}
